//------------------------------------------------------------------------------
// <auto-generated>
//     This code was manually created to replace SDK auto-generated assembly info.
//     See Turnero.csproj -> <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

[assembly: AssemblyCompany("PF Software")]
[assembly: AssemblyCopyright("2023 - PF Software")]
[assembly: AssemblyFileVersion("3.0.1")]
[assembly: AssemblyProduct("Turnero")]
[assembly: AssemblyTitle("Turnero")]
[assembly: AssemblyVersion("3.0.1")]
