name: Deploy Demo

on:
  push:
    branches: 
    - demo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Build and publish
        run: |
          dotnet publish -c Release -o ./publish
      - name: Deploy to server
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-command: |
            # Copiar Turnero.db al directorio raíz
            ssh -p ${{ secrets.PORT }} ${{ secrets.USER_NAME }}@${{ secrets.SERVER }} 'cp ${{ secrets.TURNERO_PATH }}Turnero.db ${{ secrets.ROOT_PATH }}Turnero.db'

            # Copiar archivos al directorio Turnero
            scp -r -P ${{ secrets.PORT }} ./publish/* ${{ secrets.USER_NAME }}@${{ secrets.SERVER }}:${{ secrets.TURNERO_PATH }}

            # Copiar Turnero.db de vuelta al directorio Turnero
            ssh -p ${{ secrets.PORT }} ${{ secrets.USER_NAME }}@${{ secrets.SERVER }} 'cp ${{ secrets.ROOT_PATH }}Turnero.db ${{ secrets.TURNERO_PATH }}Turnero.db'

