name: Deploy Demo

on:
  push:
    branches: 
    - demo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Build and publish
        run: |
          dotnet publish -c Release --nologo -r linux-x64 --self-contained -o ./publish
          
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: List directory
        run: ls -l ./publish/

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USER_NAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Detener servicio
            service turneroDemo stop
            
            # Copiar archivos al directorio Turnero
            scp -r ./publish/* /root/TurneroAppDemo/

            # Copiar Turnero.db de vuelta al directorio Turnero
            cp /root/Turnero.db /root/TurneroAppDemo/Turnero.db

            # Reiniciar servicio
            systemctl daemon-reload
            service turneroDemo start
