name: Deploy Demo

on:
  push:
    branches: 
    - demo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Build and publish
        run: |
          dotnet publish -c Release -o ./publish
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        env:
          HOST: ${{ secrets.SERVER }}
          USERNAME: ${{ secrets.USER_NAME }}
          PORT: ${{ secrets.PORT }}
          TURNERO_PATH: ${{ secrets.TURNERO_PATH }}
          ROOT_PATH: ${{ secrets.ROOT_PATH }}
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ssh -p ${{ secrets.PORT }} $USERNAME@$HOST 'cp ${{ env.TURNERO_PATH }}Turnero.db ${{ env.ROOT_PATH }}Turnero.db'
            debug: "Copying Turnero.db to root directory..."
            scp -r -P ${{ secrets.PORT }} ./publish/* $USERNAME@$HOST:${{ env.TURNERO_PATH }}
            debug: "Copying files to Turnero directory..."
            ssh -p ${{ secrets.PORT }} $USERNAME@$HOST 'cp ${{ env.ROOT_PATH }}Turnero.db ${{ env.TURNERO_PATH }}Turnero.db'
            debug: "Copying Turnero.db back to Turnero directory..."
            
