name: Deploy Demo

on:
  push:
    branches: 
    - demo

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
 
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.0.x
      - name: Build and publish
        run: |
          dotnet publish -c Release --nologo -r linux-x64 --self-contained -o ./publish
          
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        env:
          HOST: ${{ secrets.SERVER }}
          USERNAME: ${{ secrets.USER_NAME }}
          PORT: ${{ secrets.PORT }}
          TURNERO_PATH: ${{ secrets.TURNERO_PATH }}
          ROOT_PATH: ${{ secrets.ROOT_PATH }}
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Detener servicio
            ssh -p ${{ secrets.PORT }} $USERNAME@$HOST 'service turneroDemo stop'

            # Copiar Turnero.db al directorio raíz
            ssh -p ${{ env.PORT }} $USERNAME@$HOST 'cp ${{ env.TURNERO_PATH }}Turnero.db ${{ env.ROOT_PATH }}Turnero.db'
            ssh -p ${{ env.PORT }} $USERNAME@$HOST 'rm -rf ${{ env.TURNERO_PATH }}*'

            # Crear directorio Turnero
            ssh -p ${{ env.PORT }} $USERNAME@$HOST 'mkdir ${{ env.TURNERO_PATH }}'

            # Copiar archivos al directorio Turnero
            scp -r -P ${{ env.PORT }} ./publish/* $USERNAME@$HOST:${{ env.TURNERO_PATH }}

            # Copiar Turnero.db de vuelta al directorio Turnero
            ssh -p ${{ env.PORT }} $USERNAME@$HOST 'cp ${{ env.ROOT_PATH }}Turnero.db ${{ env.TURNERO_PATH }}Turnero.db'

            # Reiniciar servicio
            ssh -p ${{ env.PORT }} $USERNAME@$HOST 'systemctl daemon-reload'
            ssh -p ${{ env.PORT }} $USERNAME@$HOST 'service turneroDemo start'
