name: Deploy Prod

on:
  workflow_run:
    workflows: [".NET Core"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@master
      
      - name: Setup .NET
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: 8.0.x
      - name: Build and publish
        run: |
          dotnet publish -c Release --nologo -r linux-x64 --self-contained -o ./TurneroApp
          
      - name: Setup SSH
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Create ZIP
        uses: montudor/action-zip@master
        with:
          args: zip -qq -r TurneroApp.zip TurneroApp

      - name: Stop Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            # Detener servicio
            service turnero stop
    
      - name: copy file via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USER_NAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          source: TurneroApp.zip
          target: ${{ secrets.SRV_PATH }}
          
      - name: Restart Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USER_NAME }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |            
            # Reiniciar servicio
            cp ${{ secrets.SRV_PATH }}/TurneroApp/appsettings.json ${{ secrets.SRV_PATH }}/appsettings.json
            unzip -o ${{ secrets.SRV_PATH }}/TurneroApp.zip
            cp ${{ secrets.SRV_PATH }}/appsettings.json ${{ secrets.SRV_PATH }}/TurneroApp/appsettings.json
            rm ${{ secrets.SRV_PATH }}/TurneroApp.zip
            rm ${{ secrets.SRV_PATH }}/appsettings.json
            systemctl daemon-reload
            service turnero start
