name: Deploy Prod

on:
  push:
    branches: 
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@master
      
      - name: Setup .NET
        uses: actions/setup-dotnet@master
        with:
          dotnet-version: 8.0.x
      - name: Build and publish
        run: |
          dotnet publish -c Release --nologo -r linux-x64 --self-contained -o ./TurneroApp
          
      - name: Setup SSH
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      
      - name: Create ZIP
        uses: montudor/action-zip@master
        with:
          args: zip -qq -r TurneroApp.zip TurneroApp

      - name: Stop Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USER_NAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Detener servicio
            service turnero stop
    
      - name: copy file via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USER_NAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: TurneroApp.zip
          target: /root
          
      - name: Restart Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER }}
          username: ${{ secrets.USER_NAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |            
            # Reiniciar servicio
            unzip -o /root/TurneroApp.zip
            systemctl daemon-reload
            service turnero start
