name: Trigger auto deployment for turnero

on:
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/turnero-AutoDeployTrigger-a5f853b2-8fc6-4ba4-95eb-197931dcd6cc.yml'

  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write 
      contents: read 

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.TURNERO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TURNERO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TURNERO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          # Especificamos la URL completa del servidor de inicio de sesión
          registryUrl: turnero-h6bkg0ascgebeqcr.azurecr.io
          # Usamos los secrets con las credenciales de administrador de tu ACR
          registryUsername: ${{ secrets.TURNERO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TURNERO_REGISTRY_PASSWORD }}
          containerAppName: turnero
          resourceGroup: turnero
